name: SLOW5 C/C++ CI Local OSX

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  hdf5_compile:
    name: install
    runs-on: ${{ matrix.runners }}
    strategy:
      matrix:
        runners: [macOS]
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: make -j8
    - name: test
      run: make test
